---
title: "examen_parcial"
format: html
editor: visual
---

## Importar Datos

```{r}
getwd() # Ruta del archivo actual
setwd("C:/Users/dfigu/OneDrive/Documents/RStudio/datasets") # Cambiamos de directorio
getwd() # Ruta nueva (carpeta de datasets, donde accederemos a nuestro archivo csv)
DF <- read.csv(".csv") # Leemos el CSV
View(DF) # Mostrar el DF en pantalla
```

### Funciones Importantes

```{r}
library(readr)
library(dplyr)
library(modeest)
library(ggplot2)

# Calcular el coeficiente de variación
cv <- function(var) {
  return(sd(var)/mean(var))
}

resumen_estadistico <- function(vector) {
  # Calcular los valores solicitados
  minimo <- min(vector, na.rm = TRUE)
  maximo <- max(vector, na.rm = TRUE)
  rango <- maximo - minimo
  q1 <- quantile(vector, probs = 0.25, type = 3, na.rm = TRUE)
  mediana <- median(vector, na.rm = TRUE)
  q3 <- quantile(vector, probs = 0.75, type = 3, na.rm = TRUE)
  iqr <- q3 - q1
  media <- mean(vector, na.rm = TRUE)
  moda <- mfv(vector)
  desviacion_standar <- sd(vector, na.rm = TRUE)
  coeficiente_variacion <- desviacion_standar / media
  
  # Imprimir los resultados
  cat("Resumen estadístico de la variable:\n")
  cat("Mínimo:", minimo, "\n")
  cat("Máximo:", maximo, "\n")
  cat("Rango:", rango, "\n")
  cat("Cuartil 1 (Q1):", q1, "\n")
  cat("Mediana (Q2):", mediana, "\n")
  cat("Cuartil 3 (Q3):", q3, "\n")
  cat("Rango intercuartílico:", iqr, "\n")
  cat("Media:", media, "\n")
  cat("Moda:", moda, "\n")
  cat("Desviación estándar:", desviacion_standar, "\n")
  cat("Coeficiente de variación:", coeficiente_variacion, "\n")
}


```

## Pregunta 1

```{r}

```

## Pregunta 2

```{r}

```

## Pregunta 3

```{r}

```

## Pregunta 4

```{r}

```

## Pregunta 5

```{r}

```
