---
title: "q1"
format: html
editor: visual
---

## Importar librerías

```{r}
library(readr)
library(dplyr)
library(modeest)
```

## Importar csv

```{r}
setwd("C:/Users/dfigu/OneDrive/Documents/RStudio/datasets") # Cambiamos de directorio
getwd() # Comprobar ruta nueva (carpeta de datasets, donde accederemos a nuestro archivo csv)
DFO <- read.csv("cuytopia.csv") # Leemos el CSV
DF <- DFO # Pasamos el dataframe original a un nuevo dataframe, sobre el cual se realizará la limpieza
```

## Pregunta 1

```{r}
sapply(DF, function(x) sum(is.na(x) | x == ""))
str(DF)
sum(rowSums(is.na(DF) | DF == "") > 0)
```

## Preguna 2

```{r}
DFF <- DF
DFF <- DFF %>% filter(!is.na(DFF$Raza))
DFF <- DFF %>% filter(!is.na(DFF$Sexo))
DFF <- DFF %>% filter(!is.na(DFF$Peso))
DFF <- DFF %>% filter(!is.na(DFF$Largo))
DFF <- DFF %>% filter(!is.na(DFF$Cintura))
DFF <- DFF %>% filter(!is.na(DFF$Color))
DFF <- DFF %>% filter(!is.na(DFF$Talla))
DFF <- DFF %>% filter(!is.na(DFF$Edad))
min(DFF$Peso)
table(DF$Raza)
table(DF$Sexo)
table(DF$Color)
table(DF$Talla)

```

## Pregunta 3

```{r}
sd(DFF$Peso)/mean(DFF$Peso)
max(DFF$Peso)
mean(DFF$Peso)
min(DFF$Peso)
```

## Pregunta 4

```{r}
sd(DFF$Cintura)/mean(DFF$Cintura)
summary(DFF$Cintura)
```

## Pregunta 5

```{r}
sd(DFF$Largo)/mean(DFF$Largo)
summary(DFF$Talla)
median(DFF$Talla)
table(DFF$Talla)
```
