---
title: "repaso-parcial"
format: html
editor: visual
---

```{r}
setwd("/home/diego/Desktop/stats-class/datasets") # Cambiamos de directorio
getwd() # Comprobar ruta nueva (carpeta de datasets, donde accederemos a nuestro archivo csv)
DFO <- read.csv("cuytopia_limpio.csv") # Leemos el CSV
DF <- DFO # Pasamos el dataframe original a un nuevo dataframe, sobre el cual se realizará la limpieza
```

```{r}
sum(is.na(DF) | DF == "") # Cantidad de datos faltantes
sum(rowSums(is.na(DF) | DF == "") > 0) # Cantidad de observaciones incompletas
sapply(DF, function(x) sum(is.na(x) | x == "")) # Tabla con cantidad de datos faltantes por variables
mean(sapply(DF, function(x) sum(is.na(x) | x == ""))) # Promedio de datos faltantes
sum(rowSums(is.na(DF) | DF == "") >= 2)# Cantidad de filas con 2 o mas datos faltantes

DFF <- DF
DFF <- filter(DFF, apply(DFF, 1, function(x) sum(is.na(x))) < 2)


summary(DFF$Pulso)

miss_DFF <- sapply(DFF, function(x) sum(is.na(x) | x == ""))
summary(miss_DFF)
```

```{r}
sum(!complete.cases(DF))
sum(rowSums(is.na(DF)) >= 2)
DFL <- na.omit(DF)
nrow(DFL)/nrow(DF)
table(DFL$Color)
table(DF$Raza)
table(DFL$Raza)
round(mean(DFL$Cintura), 2)
table(DFL$Talla)
(557+21)/2174

table(DFL$Color[DFL$Raza == "abisinio"])

mean(DFL$Largo[DFL$Raza == "abisinio" & DFL$Color == "negro"])

```

```{r}
library(ggplot2)
hist(DFL$Peso[DFL$Raza == "abisinio"])
boxplot(DFL$Peso[DFL$Raza == "abisinio"])
DF[rowSums(is.na(DF)) <= 2]
```
