---
title: "repaso3"
format: html
editor: visual
---

## Repaso Parcial 3

### Pregunta 1

```{r}
setwd("/home/diego/Desktop/stats-class/datasets") # Cambiamos de directorio
getwd() # Comprobar ruta nueva (carpeta de datasets, donde accederemos a nuestro archivo csv)
DFO <- read.csv("piloto.csv") # Leemos el CSV
DF <- DFO # Pasamos el dataframe original a un nuevo dataframe, sobre el cual se realizará la limpieza
```

### Pregunta 2

```{r}
sum(is.na(DF)) # Num de datos faltantes en el DF
sum(is.na(DF))/sum(ncol(DF)*nrow(DF)) # % de datos faltantes (en decimal)
sum(rowSums(is.na(DF)) > 0) # Num de observaciones imcompletas
sapply(DF, function(x) sum(is.na(x))) # Datos faltantes por variable
mean(rowSums(is.na(DF))) # Promedio de datos faltantes POR OBSERVACION
```

### Pregunta 3

```{r}
DFL <- DF[!(is.na(DF$Peso) & (is.na(DF$Talla) | is.na(DF$Largo))), ] # descartar las filas donde faltan los valores de la variable Peso y al menos de una de las variables Talla o Largo
sum(is.na(DFL))
sum(rowSums(is.na(DFL)) > 0)
sapply(DF, function(x) sum(is.na(x)))
```

### Pregunta 4

```{r}
# CV ES DECIMAL
nrow(DFL) - sum(is.na(DF$Edad))
sd(DF$Edad[!is.na(DF$Edad)]) / mean(DF$Edad[!is.na(DF$Edad)])
summary(DF$Edad)
max(DF$Edad[!is.na(DF$Edad)]) - min(DF$Edad[!is.na(DF$Edad)])

```
