---
title: "tarea1"
format: html
editor: visual
toc: true
---

## Tarea 1

```{r}
x<-35+45
cat("Sumando 35 y 45 obtenemos", x)
```

```{r}
a<-c(1, 4, 6, 8)
b<-c(2, 10, 3, 7)
plot(a, b)
title(main="Gráfico de 4 puntos", col.main="purple")
```

```{r}
setwd("C:/Users/dfigu/OneDrive/Documents/RStudio/datasets") # Cambiamos de directorio
getwd() # Comprobar ruta nueva (carpeta de datasets, donde accederemos a nuestro archivo csv)
DFO <- read.csv("cuytopia.csv") # Leemos el CSV
DF <- DFO # Pasamos el dataframe original a un nuevo dataframe, sobre el cual se realizará la limpieza
```

## Tratar los datos

```{r}
library(modeest)
library(dplyr)
sum(is.na(DF))
sapply(DF, function(x) sum(is.na(x) | x == ""))
str(DF)
sum(rowSums(is.na(DF) | DF == "") > 0)
4649-1832
sum(rowSums(is.na(DF))==5)
sum(is.na(DF))/4649
median(rowSums(is.na(DF)))
summary(DF$Peso)
mfv(DF$Peso, na_rm=TRUE)
mean(DF$Peso[!is.na(DF$Peso)])
sd(DF$Peso[!is.na(DF$Peso)])
n_distinct(DF$Peso[!is.na(DF$Peso)])
```

```{r}
DF$Color[DF$Color == "Tricolor" | DF$Color == "Tricoloor"] <- "tricolor"
table(DF$Color)
```

```{r}
summary(DF$Peso)
856-680.7
sd(DF$Peso[!is.na(DF$Peso)])/mean(DF$Peso[!is.na(DF$Peso)])
max(DF$Peso[!is.na(DF$Peso)])
hist(DF$Peso[DF$Peso<10000])
```
